#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
Name     : ddd
Version  : 3.4.0
Release  : 6
URL      : https://ftp.gnu.org/gnu/ddd/ddd-3.4.0.tar.gz
Source0  : https://ftp.gnu.org/gnu/ddd/ddd-3.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-3.0 LGPL-3.0
Requires: ddd-bin = %{version}-%{release}
Requires: ddd-data = %{version}-%{release}
Requires: ddd-info = %{version}-%{release}
Requires: ddd-license = %{version}-%{release}
Requires: ddd-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : elfutils-dev
BuildRequires : flex
BuildRequires : libXaw-dev
BuildRequires : motif-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xt)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the source distribution of DDD, the Data Display Debugger.
The GNU project page for DDD can be found at
https://savannah.gnu.org/projects/ddd

%package bin
Summary: bin components for the ddd package.
Group: Binaries
Requires: ddd-data = %{version}-%{release}
Requires: ddd-license = %{version}-%{release}

%description bin
bin components for the ddd package.


%package data
Summary: data components for the ddd package.
Group: Data

%description data
data components for the ddd package.


%package info
Summary: info components for the ddd package.
Group: Default

%description info
info components for the ddd package.


%package license
Summary: license components for the ddd package.
Group: Default

%description license
license components for the ddd package.


%package man
Summary: man components for the ddd package.
Group: Default

%description man
man components for the ddd package.


%prep
%setup -q -n ddd-3.4.0
cd %{_builddir}/ddd-3.4.0
pushd ..
cp -a ddd-3.4.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701949306
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701949306
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ddd
cp %{_builddir}/ddd-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ddd/338650eb7a42dd9bc1f1c6961420f2633b24932d || :
cp %{_builddir}/ddd-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/ddd/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/ddd-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/ddd/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ddd
/usr/bin/ddd

%files data
%defattr(-,root,root,-)
/usr/share/applications/ddd.desktop
/usr/share/ddd-3.4.0/COPYING
/usr/share/ddd-3.4.0/NEWS
/usr/share/ddd-3.4.0/ddd/Ddd
/usr/share/ddd-3.4.0/themes/green.vsl
/usr/share/ddd-3.4.0/themes/red.vsl
/usr/share/ddd-3.4.0/themes/rednil.vsl
/usr/share/ddd-3.4.0/themes/smalltitles.vsl
/usr/share/ddd-3.4.0/themes/smallvalues.vsl
/usr/share/ddd-3.4.0/themes/suppress.vsl
/usr/share/ddd-3.4.0/themes/tinyvalues.vsl
/usr/share/ddd-3.4.0/themes/x86.vsl
/usr/share/ddd-3.4.0/vsllib/arcs.vsl
/usr/share/ddd-3.4.0/vsllib/builtin.vsl
/usr/share/ddd-3.4.0/vsllib/colors.vsl
/usr/share/ddd-3.4.0/vsllib/ctree.vsl
/usr/share/ddd-3.4.0/vsllib/ddd.vsl
/usr/share/ddd-3.4.0/vsllib/flow.vsl
/usr/share/ddd-3.4.0/vsllib/flowplus.vsl
/usr/share/ddd-3.4.0/vsllib/fonts.vsl
/usr/share/ddd-3.4.0/vsllib/linebreak.vsl
/usr/share/ddd-3.4.0/vsllib/list.vsl
/usr/share/ddd-3.4.0/vsllib/slopes.vsl
/usr/share/ddd-3.4.0/vsllib/std.vsl
/usr/share/ddd-3.4.0/vsllib/struct.vsl
/usr/share/ddd-3.4.0/vsllib/symbols.vsl
/usr/share/ddd-3.4.0/vsllib/tab.vsl
/usr/share/ddd-3.4.0/vsllib/tree.vsl
/usr/share/ddd-3.4.0/vsllib/verbose.vsl
/usr/share/ddd-3.4.0/vsllib/vsl.vsl
/usr/share/ddd-3.4.0/vsllib/vsldef.vsl
/usr/share/ddd-3.4.0/vsllib/vsllib.vsl

%files info
%defattr(0644,root,root,0755)
/usr/share/info/ddd-themes.info
/usr/share/info/ddd.info
/usr/share/info/ddd.info-1
/usr/share/info/ddd.info-2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ddd/338650eb7a42dd9bc1f1c6961420f2633b24932d
/usr/share/package-licenses/ddd/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/ddd/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ddd.1
