#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6656C593E5158D1A (prw@ceiriog1.demon.co.uk)
#
Name     : ddd
Version  : 3.3.12
Release  : 2
URL      : https://ftp.gnu.org/gnu/ddd/ddd-3.3.12.tar.gz
Source0  : https://ftp.gnu.org/gnu/ddd/ddd-3.3.12.tar.gz
Source1 : https://ftp.gnu.org/gnu/ddd/ddd-3.3.12.tar.gz.sig
Summary  : graphical debugger front-end; GDB, DBX, Ladebug, JDB, Perl, Python
Group    : Development/Tools
License  : GFDL-1.1 GPL-3.0 LGPL-3.0
Requires: ddd-bin = %{version}-%{release}
Requires: ddd-data = %{version}-%{release}
Requires: ddd-license = %{version}-%{release}
Requires: ddd-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : elfutils-dev
BuildRequires : flex
BuildRequires : motif-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xt)
Patch1: friend-default.patch

%description
This is the source distribution of DDD, the Data Display Debugger.
To find out what's new in DDD, see the file `NEWS'.
To find out how to build DDD, consult the file `INSTALL'.

%package bin
Summary: bin components for the ddd package.
Group: Binaries
Requires: ddd-data = %{version}-%{release}
Requires: ddd-license = %{version}-%{release}

%description bin
bin components for the ddd package.


%package data
Summary: data components for the ddd package.
Group: Data

%description data
data components for the ddd package.


%package doc
Summary: doc components for the ddd package.
Group: Documentation
Requires: ddd-man = %{version}-%{release}

%description doc
doc components for the ddd package.


%package license
Summary: license components for the ddd package.
Group: Default

%description license
license components for the ddd package.


%package man
Summary: man components for the ddd package.
Group: Default

%description man
man components for the ddd package.


%prep
%setup -q -n ddd-3.3.12
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570041674
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1570041674
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ddd
cp COPYING %{buildroot}/usr/share/package-licenses/ddd/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/ddd/COPYING.DOC
cp COPYING.LESSER %{buildroot}/usr/share/package-licenses/ddd/COPYING.LESSER
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ddd

%files data
%defattr(-,root,root,-)
/usr/share/applications/ddd.desktop
/usr/share/ddd-3.3.12/COPYING
/usr/share/ddd-3.3.12/NEWS
/usr/share/ddd-3.3.12/ddd/Ddd
/usr/share/ddd-3.3.12/themes/green.vsl
/usr/share/ddd-3.3.12/themes/red.vsl
/usr/share/ddd-3.3.12/themes/rednil.vsl
/usr/share/ddd-3.3.12/themes/smalltitles.vsl
/usr/share/ddd-3.3.12/themes/smallvalues.vsl
/usr/share/ddd-3.3.12/themes/suppress.vsl
/usr/share/ddd-3.3.12/themes/tinyvalues.vsl
/usr/share/ddd-3.3.12/themes/x86.vsl
/usr/share/ddd-3.3.12/vsllib/arcs.vsl
/usr/share/ddd-3.3.12/vsllib/builtin.vsl
/usr/share/ddd-3.3.12/vsllib/colors.vsl
/usr/share/ddd-3.3.12/vsllib/ctree.vsl
/usr/share/ddd-3.3.12/vsllib/ddd.vsl
/usr/share/ddd-3.3.12/vsllib/flow.vsl
/usr/share/ddd-3.3.12/vsllib/flowplus.vsl
/usr/share/ddd-3.3.12/vsllib/fonts.vsl
/usr/share/ddd-3.3.12/vsllib/linebreak.vsl
/usr/share/ddd-3.3.12/vsllib/list.vsl
/usr/share/ddd-3.3.12/vsllib/slopes.vsl
/usr/share/ddd-3.3.12/vsllib/std.vsl
/usr/share/ddd-3.3.12/vsllib/struct.vsl
/usr/share/ddd-3.3.12/vsllib/symbols.vsl
/usr/share/ddd-3.3.12/vsllib/tab.vsl
/usr/share/ddd-3.3.12/vsllib/tree.vsl
/usr/share/ddd-3.3.12/vsllib/verbose.vsl
/usr/share/ddd-3.3.12/vsllib/vsl.vsl
/usr/share/ddd-3.3.12/vsllib/vsldef.vsl
/usr/share/ddd-3.3.12/vsllib/vsllib.vsl

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ddd/COPYING
/usr/share/package-licenses/ddd/COPYING.DOC
/usr/share/package-licenses/ddd/COPYING.LESSER

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ddd.1
